In [1]:
#Data Manipulation specific
import numpy as np
import pandas as pd
import xarray as xr
#import scipy.stats as stats
#from scipy import signal
from netCDF4 import Dataset
 
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

import rasterio
from rasterio.transform import from_origin

import os

/home/anas.oubaha/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [5]:
!free -g

              total        used        free      shared  buff/cache   available
Mem:            376          53         148           1         173         317
Swap:             0           0           0

In [1]:
!pwd

/home/anas.oubaha/ondemand/data/sys/dashboard/batch_connect/sys/bc_desktop/slurm

In [ ]:
!zip -r notebooks.zip CAPE.ipynb GPH.ipynb SST.ipynb VIMDF

In [7]:
!zip -r output.zip Wind850 VIMDF CAPE GPH850 RH200 RH850 GPH200 Wind200

  adding: Wind850/ (stored 0%)
  adding: Wind850/SON 2005.tif (deflated 9%)
  adding: Wind850/DJF 2019.tif (deflated 8%)
  adding: Wind850/MAM 2017.tif (deflated 8%)
  adding: Wind850/SON 2008.tif (deflated 9%)
  adding: Wind850/DJF 1995.tif (deflated 8%)
  adding: Wind850/DJF 2015.tif (deflated 8%)
  adding: Wind850/DJF 2000.tif (deflated 8%)
  adding: Wind850/SON 1992.tif (deflated 9%)
  adding: Wind850/JJA 2018.tif (deflated 9%)
  adding: Wind850/SON 2000.tif (deflated 8%)
  adding: Wind850/JJA 2022.tif (deflated 8%)
  adding: Wind850/JJA 2006.tif (deflated 9%)
  adding: Wind850/MAM 2004.tif (deflated 8%)
  adding: Wind850/JJA 2023.tif (deflated 8%)
  adding: Wind850/MAM 2006.tif (deflated 8%)
  adding: Wind850/DJF 2010.tif (deflated 8%)
  adding: Wind850/MAM 2003.tif (deflated 8%)
  adding: Wind850/SON 2020.tif (deflated 9%)
  adding: Wind850/JJA 1993.tif (deflated 8%)
  adding: Wind850/MAM 2002.tif (deflated 8%)
  adding: Wind850/JJA 2007.tif (deflated 9%)
  adding: Wind850/DJF 2022.tif (deflated 8%)
  adding: Wind850/JJA 2005.tif (deflated 9%)
  adding: Wind850/SON 1993.tif (deflated 9%)
  adding: Wind850/MAM 1994.tif (deflated 8%)
  adding: Wind850/SON 2006.tif (deflated 9%)
  adding: Wind850/JJA 1997.tif (deflated 9%)
  adding: Wind850/MAM 2009.tif (deflated 8%)
  adding: Wind850/DJF 2002.tif (deflated 8%)
  adding: Wind850/JJA 1995.tif (deflated 9%)
  adding: Wind850/DJF 2023.tif (deflated 8%)
  adding: Wind850/DJF 1997.tif (deflated 8%)
  adding: Wind850/JJA 2024.tif (deflated 9%)
  adding: Wind850/JJA 2016.tif (deflated 9%)
  adding: Wind850/JJA 1999.tif (deflated 9%)
  adding: Wind850/DJF 2011.tif (deflated 8%)
  adding: Wind850/DJF 2003.tif (deflated 8%)
  adding: Wind850/DJF 1999.tif (deflated 8%)
  adding: Wind850/JJA 2009.tif (deflated 8%)
  adding: Wind850/SON 1996.tif (deflated 9%)
  adding: Wind850/MAM 1998.tif (deflated 8%)
  adding: Wind850/DJF 2008.tif (deflated 8%)
  adding: Wind850/DJF 2018.tif (deflated 8%)
  adding: Wind850/SON 2002.tif (deflated 9%)
  adding: Wind850/MAM 2012.tif (deflated 8%)
  adding: Wind850/DJF 2025.tif (deflated 8%)
  adding: Wind850/DJF 2020.tif (deflated 8%)
  adding: Wind850/SON 2024.tif (deflated 9%)
  adding: Wind850/JJA 1991.tif (deflated 9%)
  adding: Wind850/DJF 2007.tif (deflated 8%)
  adding: Wind850/MAM 2008.tif (deflated 8%)
  adding: Wind850/DJF 2012.tif (deflated 8%)
  adding: Wind850/JJA 2015.tif (deflated 8%)
  adding: Wind850/MAM 2023.tif (deflated 8%)
  adding: Wind850/JJA 2011.tif (deflated 9%)
  adding: Wind850/MAM 2007.tif (deflated 8%)
  adding: Wind850/JJA 2002.tif (deflated 9%)
  adding: Wind850/MAM 2018.tif (deflated 8%)
  adding: Wind850/DJF 2004.tif (deflated 8%)
  adding: Wind850/SON 1997.tif (deflated 9%)
  adding: Wind850/SON 2013.tif (deflated 9%)
  adding: Wind850/SON 2010.tif (deflated 9%)
  adding: Wind850/JJA 2014.tif (deflated 9%)
  adding: Wind850/JJA 2017.tif (deflated 9%)
  adding: Wind850/JJA 2008.tif (deflated 9%)
  adding: Wind850/SON 2021.tif (deflated 9%)
  adding: Wind850/DJF 2009.tif (deflated 8%)
  adding: Wind850/MAM 2010.tif (deflated 8%)
  adding: Wind850/JJA 2004.tif (deflated 9%)
  adding: Wind850/SON 2009.tif (deflated 9%)
  adding: Wind850/MAM 2005.tif (deflated 8%)
  adding: Wind850/SON 2019.tif (deflated 9%)
  adding: Wind850/JJA 1992.tif (deflated 9%)
  adding: Wind850/DJF 1994.tif (deflated 8%)
  adding: Wind850/JJA 2021.tif (deflated 9%)
  adding: Wind850/JJA 1994.tif (deflated 9%)
  adding: Wind850/MAM 1992.tif (deflated 8%)
  adding: Wind850/MAM 1999.tif (deflated 8%)
  adding: Wind850/SON 1991.tif (deflated 9%)
  adding: Wind850/MAM 2015.tif (deflated 8%)
  adding: Wind850/MAM 2016.tif (deflated 9%)
  adding: Wind850/JJA 2019.tif (deflated 9%)
  adding: Wind850/SON 1999.tif (deflated 9%)
  adding: Wind850/SON 2018.tif (deflated 9%)
  adding: Wind850/MAM 2019.tif (deflated 8%)
  adding: Wind850/MAM 2011.tif (deflated 8%)
  adding: Wind850/JJA 2013.tif (deflated 9%)
  adding: Wind850/SON 2001.tif (deflated 9%)
  adding: Wind850/MAM 1993.tif (deflated 8%)
  adding: Wind850/SON 2003.tif (deflated 9%)
  adding: Wind850/DJF 2016.tif (deflated 8%)
  adding: Wind850/SON 2011.tif (deflated 9%)
  adding: Wind850/MAM 2013.tif (deflated 8%)
  adding: Wind850/DJF 1992.tif (deflated 8%)
  adding: Wind850/DJF 1993.tif (deflated 8%)
  adding: Wind850/SON 1998.tif (deflated 9%)
  adding: Wind850/SON 2022.tif (deflated 9%)
  adding: Wind850/DJF 1998.tif (deflated 8%)
  adding: Wind850/MAM 1997.tif (deflated 8%)
  adding: Wind850/SON 2023.tif (deflated 9%)
  adding: Wind850/DJF 2001.tif (deflated 8%)
  adding: Wind850/JJA 2010.tif (deflated 9%)
  adding: Wind850/DJF 2024.tif (deflated 8%)
  adding: Wind850/SON 1994.tif (deflated 9%)
  adding: Wind850/MAM 2020.tif (deflated 9%)
  adding: Wind850/JJA 1996.tif (deflated 9%)
  adding: Wind850/SON 2017.tif (deflated 9%)
  adding: Wind850/MAM 1995.tif (deflated 8%)
  adding: Wind850/SON 2004.tif (deflated 9%)
  adding: Wind850/DJF 2017.tif (deflated 8%)
  adding: Wind850/JJA 2000.tif (deflated 9%)
  adding: Wind850/DJF 2005.tif (deflated 8%)
  adding: Wind850/MAM 1996.tif (deflated 8%)
  adding: Wind850/SON 2012.tif (deflated 9%)
  adding: Wind850/SON 1995.tif (deflated 9%)
  adding: Wind850/MAM 2000.tif (deflated 8%)
  adding: Wind850/SON 2014.tif (deflated 9%)
  adding: Wind850/MAM 2014.tif (deflated 8%)
  adding: Wind850/MAM 2022.tif (deflated 8%)
  adding: Wind850/DJF 2014.tif (deflated 8%)
  adding: Wind850/DJF 1991.tif (deflated 8%)
  adding: Wind850/JJA 2003.tif (deflated 9%)
  adding: Wind850/DJF 2013.tif (deflated 8%)
  adding: Wind850/MAM 1991.tif (deflated 8%)
  adding: Wind850/DJF 2021.tif (deflated 8%)
  adding: Wind850/SON 2007.tif (deflated 9%)
  adding: Wind850/MAM 2001.tif (deflated 8%)
  adding: Wind850/JJA 2001.tif (deflated 9%)
  adding: Wind850/SON 2015.tif (deflated 9%)
  adding: Wind850/DJF 2006.tif (deflated 8%)
  adding: Wind850/JJA 2012.tif (deflated 9%)
  adding: Wind850/SON 2016.tif (deflated 9%)
  adding: Wind850/MAM 2021.tif (deflated 8%)
  adding: Wind850/DJF 1996.tif (deflated 8%)
  adding: Wind850/JJA 2020.tif (deflated 9%)
  adding: Wind850/JJA 1998.tif (deflated 9%)
  adding: Wind850/MAM 2024.tif (deflated 8%)
  adding: VIMDF/ (stored 0%)
  adding: VIMDF/SON 2005.tif (deflated 7%)
  adding: VIMDF/DJF 2019.tif (deflated 7%)
  adding: VIMDF/MAM 2017.tif (deflated 7%)
  adding: VIMDF/SON 2008.tif (deflated 7%)
  adding: VIMDF/DJF 1995.tif (deflated 7%)
  adding: VIMDF/DJF 2015.tif (deflated 7%)
  adding: VIMDF/DJF 2000.tif (deflated 7%)
  adding: VIMDF/SON 1992.tif (deflated 7%)
  adding: VIMDF/JJA 2018.tif (deflated 7%)
  adding: VIMDF/SON 2000.tif (deflated 7%)
  adding: VIMDF/JJA 2022.tif (deflated 7%)
  adding: VIMDF/JJA 2006.tif (deflated 7%)
  adding: VIMDF/MAM 2004.tif (deflated 7%)
  adding: VIMDF/JJA 2023.tif (deflated 7%)
  adding: VIMDF/MAM 2006.tif (deflated 7%)
  adding: VIMDF/DJF 2010.tif (deflated 7%)
  adding: VIMDF/MAM 2003.tif (deflated 7%)
  adding: VIMDF/SON 2020.tif (deflated 7%)
  adding: VIMDF/JJA 1993.tif (deflated 7%)
  adding: VIMDF/MAM 2002.tif (deflated 7%)
  adding: VIMDF/JJA 2007.tif (deflated 7%)
  adding: VIMDF/DJF 2022.tif (deflated 7%)
  adding: VIMDF/JJA 2005.tif (deflated 7%)
  adding: VIMDF/SON 1993.tif (deflated 7%)
  adding: VIMDF/MAM 1994.tif (deflated 7%)
  adding: VIMDF/SON 2006.tif (deflated 7%)
  adding: VIMDF/JJA 1997.tif (deflated 7%)
  adding: VIMDF/MAM 2009.tif (deflated 7%)
  adding: VIMDF/DJF 2002.tif (deflated 7%)
  adding: VIMDF/JJA 1995.tif (deflated 7%)
  adding: VIMDF/DJF 2023.tif (deflated 7%)
  adding: VIMDF/DJF 1997.tif (deflated 7%)
  adding: VIMDF/JJA 2024.tif (deflated 7%)
  adding: VIMDF/JJA 2016.tif (deflated 7%)
  adding: VIMDF/JJA 1999.tif (deflated 7%)
  adding: VIMDF/DJF 2011.tif (deflated 7%)
  adding: VIMDF/DJF 2003.tif (deflated 7%)
  adding: VIMDF/DJF 1999.tif (deflated 7%)
  adding: VIMDF/JJA 2009.tif (deflated 7%)
  adding: VIMDF/SON 1996.tif (deflated 7%)
  adding: VIMDF/MAM 1998.tif (deflated 7%)
  adding: VIMDF/DJF 2008.tif (deflated 7%)
  adding: VIMDF/DJF 2018.tif (deflated 7%)
  adding: VIMDF/SON 2002.tif (deflated 7%)
  adding: VIMDF/MAM 2012.tif (deflated 7%)
  adding: VIMDF/DJF 2025.tif (deflated 7%)

  adding: VIMDF/DJF 2020.tif (deflated 7%)
  adding: VIMDF/SON 2024.tif (deflated 7%)
  adding: VIMDF/JJA 1991.tif (deflated 7%)
  adding: VIMDF/DJF 2007.tif (deflated 7%)
  adding: VIMDF/MAM 2008.tif (deflated 7%)
  adding: VIMDF/DJF 2012.tif (deflated 7%)
  adding: VIMDF/JJA 2015.tif (deflated 7%)
  adding: VIMDF/MAM 2023.tif (deflated 7%)
  adding: VIMDF/JJA 2011.tif (deflated 7%)
  adding: VIMDF/MAM 2007.tif (deflated 7%)
  adding: VIMDF/JJA 2002.tif (deflated 7%)
  adding: VIMDF/MAM 2018.tif (deflated 7%)
  adding: VIMDF/DJF 2004.tif (deflated 7%)
  adding: VIMDF/SON 1997.tif (deflated 7%)
  adding: VIMDF/SON 2013.tif (deflated 7%)
  adding: VIMDF/SON 2010.tif (deflated 7%)
  adding: VIMDF/JJA 2014.tif (deflated 7%)
  adding: VIMDF/JJA 2017.tif (deflated 7%)
  adding: VIMDF/JJA 2008.tif (deflated 7%)
  adding: VIMDF/SON 2021.tif (deflated 7%)
  adding: VIMDF/DJF 2009.tif (deflated 7%)
  adding: VIMDF/MAM 2010.tif (deflated 7%)
  adding: VIMDF/JJA 2004.tif (deflated 7%)
  adding: VIMDF/SON 2009.tif (deflated 7%)
  adding: VIMDF/MAM 2005.tif (deflated 7%)
  adding: VIMDF/SON 2019.tif (deflated 7%)
  adding: VIMDF/JJA 1992.tif (deflated 7%)
  adding: VIMDF/DJF 1994.tif (deflated 7%)
  adding: VIMDF/JJA 2021.tif (deflated 7%)
  adding: VIMDF/JJA 1994.tif (deflated 7%)
  adding: VIMDF/MAM 1992.tif (deflated 7%)
  adding: VIMDF/MAM 1999.tif (deflated 7%)
  adding: VIMDF/SON 1991.tif (deflated 7%)
  adding: VIMDF/MAM 2015.tif (deflated 7%)
  adding: VIMDF/MAM 2016.tif (deflated 7%)
  adding: VIMDF/JJA 2019.tif (deflated 7%)
  adding: VIMDF/SON 1999.tif (deflated 7%)
  adding: VIMDF/SON 2018.tif (deflated 7%)
  adding: VIMDF/MAM 2019.tif (deflated 7%)
  adding: VIMDF/MAM 2011.tif (deflated 7%)
  adding: VIMDF/JJA 2013.tif (deflated 7%)
  adding: VIMDF/SON 2001.tif (deflated 7%)
  adding: VIMDF/MAM 1993.tif (deflated 7%)
  adding: VIMDF/SON 2003.tif (deflated 7%)
  adding: VIMDF/DJF 2016.tif (deflated 7%)
  adding: VIMDF/SON 2011.tif (deflated 7%)
  adding: VIMDF/MAM 2013.tif (deflated 7%)
  adding: VIMDF/DJF 1992.tif (deflated 7%)
  adding: VIMDF/DJF 1993.tif (deflated 7%)
  adding: VIMDF/SON 1998.tif (deflated 7%)
  adding: VIMDF/SON 2022.tif (deflated 7%)
  adding: VIMDF/DJF 1998.tif (deflated 7%)
  adding: VIMDF/MAM 1997.tif (deflated 7%)
  adding: VIMDF/SON 2023.tif (deflated 7%)
  adding: VIMDF/DJF 2001.tif (deflated 7%)
  adding: VIMDF/JJA 2010.tif (deflated 7%)
  adding: VIMDF/DJF 2024.tif (deflated 7%)
  adding: VIMDF/SON 1994.tif (deflated 7%)
  adding: VIMDF/MAM 2020.tif (deflated 7%)
  adding: VIMDF/JJA 1996.tif (deflated 7%)
  adding: VIMDF/SON 2017.tif (deflated 7%)
  adding: VIMDF/MAM 1995.tif (deflated 7%)
  adding: VIMDF/SON 2004.tif (deflated 7%)
  adding: VIMDF/DJF 2017.tif (deflated 7%)
  adding: VIMDF/JJA 2000.tif (deflated 7%)
  adding: VIMDF/DJF 2005.tif (deflated 7%)
  adding: VIMDF/MAM 1996.tif (deflated 7%)
  adding: VIMDF/SON 2012.tif (deflated 7%)
  adding: VIMDF/SON 1995.tif (deflated 7%)
  adding: VIMDF/MAM 2000.tif (deflated 7%)
  adding: VIMDF/SON 2014.tif (deflated 7%)
  adding: VIMDF/MAM 2014.tif (deflated 7%)
  adding: VIMDF/MAM 2022.tif (deflated 7%)
  adding: VIMDF/DJF 2014.tif (deflated 7%)
  adding: VIMDF/DJF 1991.tif (deflated 7%)
  adding: VIMDF/JJA 2003.tif (deflated 7%)
  adding: VIMDF/DJF 2013.tif (deflated 7%)
  adding: VIMDF/MAM 1991.tif (deflated 7%)
  adding: VIMDF/DJF 2021.tif (deflated 7%)
  adding: VIMDF/SON 2007.tif (deflated 7%)
  adding: VIMDF/MAM 2001.tif (deflated 7%)
  adding: VIMDF/JJA 2001.tif (deflated 7%)
  adding: VIMDF/SON 2015.tif (deflated 7%)
  adding: VIMDF/DJF 2006.tif (deflated 7%)
  adding: VIMDF/JJA 2012.tif (deflated 7%)
  adding: VIMDF/SON 2016.tif (deflated 7%)
  adding: VIMDF/MAM 2021.tif (deflated 7%)
  adding: VIMDF/DJF 1996.tif (deflated 7%)
  adding: VIMDF/JJA 2020.tif (deflated 7%)
  adding: VIMDF/JJA 1998.tif (deflated 7%)
  adding: VIMDF/MAM 2024.tif (deflated 7%)
  adding: CAPE/ (stored 0%)
  adding: CAPE/SON 2005.tif (deflated 10%)
  adding: CAPE/DJF 2019.tif (deflated 10%)
  adding: CAPE/MAM 2017.tif (deflated 10%)
  adding: CAPE/SON 2008.tif (deflated 11%)
  adding: CAPE/DJF 1995.tif (deflated 10%)
  adding: CAPE/DJF 2015.tif (deflated 10%)
  adding: CAPE/DJF 2000.tif (deflated 10%)
  adding: CAPE/SON 1992.tif (deflated 10%)
  adding: CAPE/JJA 2018.tif (deflated 10%)
  adding: CAPE/SON 2000.tif (deflated 10%)
  adding: CAPE/JJA 2022.tif (deflated 10%)
  adding: CAPE/JJA 2006.tif (deflated 11%)
  adding: CAPE/MAM 2004.tif (deflated 10%)
  adding: CAPE/JJA 2023.tif (deflated 10%)
  adding: CAPE/MAM 2006.tif (deflated 10%)
  adding: CAPE/DJF 2010.tif (deflated 10%)
  adding: CAPE/MAM 2003.tif (deflated 10%)
  adding: CAPE/SON 2020.tif (deflated 10%)
  adding: CAPE/JJA 1993.tif (deflated 10%)
  adding: CAPE/MAM 2002.tif (deflated 11%)
  adding: CAPE/JJA 2007.tif (deflated 10%)
  adding: CAPE/DJF 2022.tif (deflated 10%)
  adding: CAPE/JJA 2005.tif (deflated 11%)
  adding: CAPE/SON 1993.tif (deflated 10%)
  adding: CAPE/MAM 1994.tif (deflated 11%)
  adding: CAPE/SON 2006.tif (deflated 10%)
  adding: CAPE/JJA 1997.tif (deflated 10%)
  adding: CAPE/MAM 2009.tif (deflated 10%)
  adding: CAPE/DJF 2002.tif (deflated 10%)
  adding: CAPE/JJA 1995.tif (deflated 11%)
  adding: CAPE/DJF 2023.tif (deflated 10%)
  adding: CAPE/DJF 1997.tif (deflated 10%)
  adding: CAPE/JJA 2024.tif (deflated 10%)
  adding: CAPE/JJA 2016.tif (deflated 10%)
  adding: CAPE/JJA 1999.tif (deflated 10%)
  adding: CAPE/DJF 2011.tif (deflated 10%)
  adding: CAPE/DJF 2003.tif (deflated 10%)
  adding: CAPE/DJF 1999.tif (deflated 10%)
  adding: CAPE/JJA 2009.tif (deflated 11%)
  adding: CAPE/SON 1996.tif (deflated 10%)
  adding: CAPE/MAM 1998.tif (deflated 10%)
  adding: CAPE/DJF 2008.tif (deflated 10%)
  adding: CAPE/DJF 2018.tif (deflated 10%)
  adding: CAPE/SON 2002.tif (deflated 10%)
  adding: CAPE/MAM 2012.tif (deflated 10%)
  adding: CAPE/DJF 2025.tif (deflated 10%)
  adding: CAPE/DJF 2020.tif (deflated 10%)
  adding: CAPE/SON 2024.tif (deflated 10%)
  adding: CAPE/JJA 1991.tif (deflated 10%)
  adding: CAPE/DJF 2007.tif (deflated 10%)
  adding: CAPE/MAM 2008.tif (deflated 10%)
  adding: CAPE/DJF 2012.tif (deflated 10%)
  adding: CAPE/JJA 2015.tif (deflated 10%)
  adding: CAPE/MAM 2023.tif (deflated 10%)
  adding: CAPE/JJA 2011.tif (deflated 10%)
  adding: CAPE/MAM 2007.tif (deflated 10%)
  adding: CAPE/JJA 2002.tif (deflated 11%)
  adding: CAPE/MAM 2018.tif (deflated 10%)
  adding: CAPE/DJF 2004.tif (deflated 10%)
  adding: CAPE/SON 1997.tif (deflated 10%)
  adding: CAPE/SON 2013.tif (deflated 10%)
  adding: CAPE/SON 2010.tif (deflated 10%)
  adding: CAPE/JJA 2014.tif (deflated 10%)
  adding: CAPE/JJA 2017.tif (deflated 11%)
  adding: CAPE/JJA 2008.tif (deflated 11%)
  adding: CAPE/SON 2021.tif (deflated 10%)
  adding: CAPE/DJF 2009.tif (deflated 10%)
  adding: CAPE/MAM 2010.tif (deflated 10%)
  adding: CAPE/JJA 2004.tif (deflated 11%)
  adding: CAPE/SON 2009.tif (deflated 11%)
  adding: CAPE/MAM 2005.tif (deflated 10%)
  adding: CAPE/SON 2019.tif (deflated 10%)
  adding: CAPE/JJA 1992.tif (deflated 11%)
  adding: CAPE/DJF 1994.tif (deflated 10%)
  adding: CAPE/JJA 2021.tif (deflated 10%)
  adding: CAPE/JJA 1994.tif (deflated 10%)
  adding: CAPE/MAM 1992.tif (deflated 10%)
  adding: CAPE/MAM 1999.tif (deflated 10%)
  adding: CAPE/SON 1991.tif (deflated 10%)
  adding: CAPE/MAM 2015.tif (deflated 10%)
  adding: CAPE/MAM 2016.tif (deflated 10%)
  adding: CAPE/JJA 2019.tif (deflated 10%)
  adding: CAPE/SON 1999.tif (deflated 10%)
  adding: CAPE/SON 2018.tif (deflated 10%)
  adding: CAPE/MAM 2019.tif (deflated 10%)
  adding: CAPE/MAM 2011.tif (deflated 10%)
  adding: CAPE/JJA 2013.tif (deflated 10%)
  adding: CAPE/SON 2001.tif (deflated 10%)
  adding: CAPE/MAM 1993.tif (deflated 10%)
  adding: CAPE/SON 2003.tif (deflated 10%)
  adding: CAPE/DJF 2016.tif (deflated 10%)
  adding: CAPE/SON 2011.tif (deflated 11%)
  adding: CAPE/MAM 2013.tif (deflated 10%)
  adding: CAPE/DJF 1992.tif (deflated 10%)
  adding: CAPE/DJF 1993.tif (deflated 10%)
  adding: CAPE/SON 1998.tif (deflated 10%)
  adding: CAPE/SON 2022.tif (deflated 10%)
  adding: CAPE/DJF 1998.tif (deflated 10%)
  adding: CAPE/MAM 1997.tif (deflated 10%)

  adding: CAPE/SON 2023.tif (deflated 10%)
  adding: CAPE/DJF 2001.tif (deflated 10%)
  adding: CAPE/JJA 2010.tif (deflated 10%)
  adding: CAPE/DJF 2024.tif (deflated 10%)
  adding: CAPE/SON 1994.tif (deflated 10%)
  adding: CAPE/MAM 2020.tif (deflated 10%)
  adding: CAPE/JJA 1996.tif (deflated 10%)
  adding: CAPE/SON 2017.tif (deflated 10%)
  adding: CAPE/MAM 1995.tif (deflated 10%)
  adding: CAPE/SON 2004.tif (deflated 11%)
  adding: CAPE/DJF 2017.tif (deflated 10%)
  adding: CAPE/JJA 2000.tif (deflated 11%)
  adding: CAPE/DJF 2005.tif (deflated 10%)
  adding: CAPE/MAM 1996.tif (deflated 10%)
  adding: CAPE/SON 2012.tif (deflated 11%)
  adding: CAPE/SON 1995.tif (deflated 10%)
  adding: CAPE/MAM 2000.tif (deflated 10%)
  adding: CAPE/SON 2014.tif (deflated 10%)
  adding: CAPE/MAM 2014.tif (deflated 10%)
  adding: CAPE/MAM 2022.tif (deflated 10%)
  adding: CAPE/DJF 2014.tif (deflated 10%)
  adding: CAPE/DJF 1991.tif (deflated 11%)
  adding: CAPE/JJA 2003.tif (deflated 10%)
  adding: CAPE/DJF 2013.tif (deflated 10%)
  adding: CAPE/MAM 1991.tif (deflated 10%)
  adding: CAPE/DJF 2021.tif (deflated 10%)
  adding: CAPE/SON 2007.tif (deflated 11%)
  adding: CAPE/MAM 2001.tif (deflated 10%)
  adding: CAPE/JJA 2001.tif (deflated 10%)
  adding: CAPE/SON 2015.tif (deflated 10%)
  adding: CAPE/DJF 2006.tif (deflated 10%)
  adding: CAPE/JJA 2012.tif (deflated 11%)
  adding: CAPE/SON 2016.tif (deflated 10%)
  adding: CAPE/MAM 2021.tif (deflated 10%)
  adding: CAPE/DJF 1996.tif (deflated 10%)
  adding: CAPE/JJA 2020.tif (deflated 10%)
  adding: CAPE/JJA 1998.tif (deflated 10%)
  adding: CAPE/MAM 2024.tif (deflated 10%)
  adding: GPH850/ (stored 0%)
  adding: GPH850/SON 2005.tif (deflated 18%)
  adding: GPH850/DJF 2019.tif (deflated 16%)
  adding: GPH850/MAM 2017.tif (deflated 17%)
  adding: GPH850/SON 2008.tif (deflated 18%)
  adding: GPH850/DJF 1995.tif (deflated 17%)
  adding: GPH850/DJF 2015.tif (deflated 16%)
  adding: GPH850/DJF 2000.tif (deflated 16%)
  adding: GPH850/SON 1992.tif (deflated 18%)
  adding: GPH850/JJA 2018.tif (deflated 18%)
  adding: GPH850/SON 2000.tif (deflated 17%)
  adding: GPH850/JJA 2022.tif (deflated 17%)
  adding: GPH850/JJA 2006.tif (deflated 18%)
  adding: GPH850/MAM 2004.tif (deflated 17%)
  adding: GPH850/JJA 2023.tif (deflated 17%)
  adding: GPH850/MAM 2006.tif (deflated 16%)
  adding: GPH850/DJF 2010.tif (deflated 16%)
  adding: GPH850/MAM 2003.tif (deflated 16%)
  adding: GPH850/SON 2020.tif (deflated 17%)
  adding: GPH850/JJA 1993.tif (deflated 18%)
  adding: GPH850/MAM 2002.tif (deflated 17%)
  adding: GPH850/JJA 2007.tif (deflated 18%)
  adding: GPH850/DJF 2022.tif (deflated 16%)
  adding: GPH850/JJA 2005.tif (deflated 18%)
  adding: GPH850/SON 1993.tif (deflated 17%)
  adding: GPH850/MAM 1994.tif (deflated 17%)
  adding: GPH850/SON 2006.tif (deflated 17%)
  adding: GPH850/JJA 1997.tif (deflated 17%)
  adding: GPH850/MAM 2009.tif (deflated 17%)
  adding: GPH850/DJF 2002.tif (deflated 16%)
  adding: GPH850/JJA 1995.tif (deflated 17%)
  adding: GPH850/DJF 2023.tif (deflated 16%)
  adding: GPH850/DJF 1997.tif (deflated 16%)
  adding: GPH850/JJA 2024.tif (deflated 17%)
  adding: GPH850/JJA 2016.tif (deflated 18%)
  adding: GPH850/JJA 1999.tif (deflated 18%)
  adding: GPH850/DJF 2011.tif (deflated 16%)
  adding: GPH850/DJF 2003.tif (deflated 17%)
  adding: GPH850/DJF 1999.tif (deflated 16%)
  adding: GPH850/JJA 2009.tif (deflated 17%)
  adding: GPH850/SON 1996.tif (deflated 17%)
  adding: GPH850/MAM 1998.tif (deflated 17%)
  adding: GPH850/DJF 2008.tif (deflated 16%)
  adding: GPH850/DJF 2018.tif (deflated 16%)
  adding: GPH850/SON 2002.tif (deflated 17%)
  adding: GPH850/MAM 2012.tif (deflated 17%)
  adding: GPH850/DJF 2025.tif (deflated 15%)
  adding: GPH850/DJF 2020.tif (deflated 16%)
  adding: GPH850/SON 2024.tif (deflated 17%)
  adding: GPH850/JJA 1991.tif (deflated 18%)
  adding: GPH850/DJF 2007.tif (deflated 17%)
  adding: GPH850/MAM 2008.tif (deflated 16%)
  adding: GPH850/DJF 2012.tif (deflated 15%)
  adding: GPH850/JJA 2015.tif (deflated 17%)
  adding: GPH850/MAM 2023.tif (deflated 16%)
  adding: GPH850/JJA 2011.tif (deflated 18%)
  adding: GPH850/MAM 2007.tif (deflated 16%)
  adding: GPH850/JJA 2002.tif (deflated 18%)
  adding: GPH850/MAM 2018.tif (deflated 15%)
  adding: GPH850/DJF 2004.tif (deflated 17%)
  adding: GPH850/SON 1997.tif (deflated 17%)
  adding: GPH850/SON 2013.tif (deflated 18%)
  adding: GPH850/SON 2010.tif (deflated 17%)
  adding: GPH850/JJA 2014.tif (deflated 18%)
  adding: GPH850/JJA 2017.tif (deflated 18%)
  adding: GPH850/JJA 2008.tif (deflated 18%)
  adding: GPH850/SON 2021.tif (deflated 17%)
  adding: GPH850/DJF 2009.tif (deflated 16%)
  adding: GPH850/MAM 2010.tif (deflated 16%)
  adding: GPH850/JJA 2004.tif (deflated 18%)
  adding: GPH850/SON 2009.tif (deflated 18%)
  adding: GPH850/MAM 2005.tif (deflated 16%)
  adding: GPH850/SON 2019.tif (deflated 17%)
  adding: GPH850/JJA 1992.tif (deflated 18%)
  adding: GPH850/DJF 1994.tif (deflated 17%)
  adding: GPH850/JJA 2021.tif (deflated 18%)
  adding: GPH850/JJA 1994.tif (deflated 17%)
  adding: GPH850/MAM 1992.tif (deflated 16%)
  adding: GPH850/MAM 1999.tif (deflated 16%)
  adding: GPH850/SON 1991.tif (deflated 18%)
  adding: GPH850/MAM 2015.tif (deflated 16%)
  adding: GPH850/MAM 2016.tif (deflated 16%)
  adding: GPH850/JJA 2019.tif (deflated 17%)
  adding: GPH850/SON 1999.tif (deflated 18%)
  adding: GPH850/SON 2018.tif (deflated 17%)
  adding: GPH850/MAM 2019.tif (deflated 17%)
  adding: GPH850/MAM 2011.tif (deflated 16%)
  adding: GPH850/JJA 2013.tif (deflated 17%)
  adding: GPH850/SON 2001.tif (deflated 18%)
  adding: GPH850/MAM 1993.tif (deflated 16%)
  adding: GPH850/SON 2003.tif (deflated 18%)
  adding: GPH850/DJF 2016.tif (deflated 16%)
  adding: GPH850/SON 2011.tif (deflated 17%)
  adding: GPH850/MAM 2013.tif (deflated 16%)
  adding: GPH850/DJF 1992.tif (deflated 15%)
  adding: GPH850/DJF 1993.tif (deflated 16%)
  adding: GPH850/SON 1998.tif (deflated 17%)
  adding: GPH850/SON 2022.tif (deflated 17%)
  adding: GPH850/DJF 1998.tif (deflated 16%)
  adding: GPH850/MAM 1997.tif (deflated 16%)
  adding: GPH850/SON 2023.tif (deflated 17%)
  adding: GPH850/DJF 2001.tif (deflated 16%)
  adding: GPH850/JJA 2010.tif (deflated 17%)
  adding: GPH850/DJF 2024.tif (deflated 16%)
  adding: GPH850/SON 1994.tif (deflated 17%)
  adding: GPH850/MAM 2020.tif (deflated 16%)
  adding: GPH850/JJA 1996.tif (deflated 18%)
  adding: GPH850/SON 2017.tif (deflated 17%)
  adding: GPH850/MAM 1995.tif (deflated 16%)
  adding: GPH850/SON 2004.tif (deflated 17%)
  adding: GPH850/DJF 2017.tif (deflated 16%)
  adding: GPH850/JJA 2000.tif (deflated 18%)
  adding: GPH850/DJF 2005.tif (deflated 16%)
  adding: GPH850/MAM 1996.tif (deflated 16%)
  adding: GPH850/SON 2012.tif (deflated 17%)
  adding: GPH850/SON 1995.tif (deflated 17%)
  adding: GPH850/MAM 2000.tif (deflated 16%)
  adding: GPH850/SON 2014.tif (deflated 17%)
  adding: GPH850/MAM 2014.tif (deflated 17%)
  adding: GPH850/MAM 2022.tif (deflated 16%)
  adding: GPH850/DJF 2014.tif (deflated 16%)
  adding: GPH850/DJF 1991.tif (deflated 16%)
  adding: GPH850/JJA 2003.tif (deflated 18%)
  adding: GPH850/DJF 2013.tif (deflated 16%)
  adding: GPH850/MAM 1991.tif (deflated 16%)
  adding: GPH850/DJF 2021.tif (deflated 16%)
  adding: GPH850/SON 2007.tif (deflated 17%)
  adding: GPH850/MAM 2001.tif (deflated 16%)
  adding: GPH850/JJA 2001.tif (deflated 18%)
  adding: GPH850/SON 2015.tif (deflated 18%)
  adding: GPH850/DJF 2006.tif (deflated 16%)
  adding: GPH850/JJA 2012.tif (deflated 17%)
  adding: GPH850/SON 2016.tif (deflated 17%)
  adding: GPH850/MAM 2021.tif (deflated 16%)
  adding: GPH850/DJF 1996.tif (deflated 16%)
  adding: GPH850/JJA 2020.tif (deflated 18%)
  adding: GPH850/JJA 1998.tif (deflated 18%)
  adding: GPH850/MAM 2024.tif (deflated 16%)
  adding: RH200/ (stored 0%)
  adding: RH200/SON 2005.tif (deflated 10%)
  adding: RH200/DJF 2019.tif (deflated 9%)
  adding: RH200/MAM 2017.tif (deflated 9%)
  adding: RH200/SON 2008.tif (deflated 10%)
  adding: RH200/DJF 1995.tif (deflated 9%)
  adding: RH200/DJF 2015.tif (deflated 9%)
  adding: RH200/DJF 2000.tif (deflated 9%)
  adding: RH200/SON 1992.tif (deflated 10%)

  adding: RH200/JJA 2018.tif (deflated 10%)
  adding: RH200/SON 2000.tif (deflated 10%)
  adding: RH200/JJA 2022.tif (deflated 9%)
  adding: RH200/JJA 2006.tif (deflated 10%)
  adding: RH200/MAM 2004.tif (deflated 9%)
  adding: RH200/JJA 2023.tif (deflated 10%)
  adding: RH200/MAM 2006.tif (deflated 9%)
  adding: RH200/DJF 2010.tif (deflated 9%)
  adding: RH200/MAM 2003.tif (deflated 9%)
  adding: RH200/SON 2020.tif (deflated 10%)
  adding: RH200/JJA 1993.tif (deflated 10%)
  adding: RH200/MAM 2002.tif (deflated 10%)
  adding: RH200/JJA 2007.tif (deflated 10%)
  adding: RH200/DJF 2022.tif (deflated 9%)
  adding: RH200/JJA 2005.tif (deflated 10%)
  adding: RH200/SON 1993.tif (deflated 10%)
  adding: RH200/MAM 1994.tif (deflated 10%)
  adding: RH200/SON 2006.tif (deflated 9%)
  adding: RH200/JJA 1997.tif (deflated 9%)
  adding: RH200/MAM 2009.tif (deflated 9%)
  adding: RH200/DJF 2002.tif (deflated 9%)
  adding: RH200/JJA 1995.tif (deflated 10%)
  adding: RH200/DJF 2023.tif (deflated 10%)
  adding: RH200/DJF 1997.tif (deflated 9%)
  adding: RH200/JJA 2024.tif (deflated 10%)
  adding: RH200/JJA 2016.tif (deflated 10%)
  adding: RH200/JJA 1999.tif (deflated 10%)
  adding: RH200/DJF 2011.tif (deflated 9%)
  adding: RH200/DJF 2003.tif (deflated 9%)
  adding: RH200/DJF 1999.tif (deflated 9%)
  adding: RH200/JJA 2009.tif (deflated 9%)
  adding: RH200/SON 1996.tif (deflated 10%)
  adding: RH200/MAM 1998.tif (deflated 9%)
  adding: RH200/DJF 2008.tif (deflated 9%)
  adding: RH200/DJF 2018.tif (deflated 9%)
  adding: RH200/SON 2002.tif (deflated 9%)
  adding: RH200/MAM 2012.tif (deflated 10%)
  adding: RH200/DJF 2025.tif (deflated 9%)
  adding: RH200/DJF 2020.tif (deflated 9%)
  adding: RH200/SON 2024.tif (deflated 10%)
  adding: RH200/JJA 1991.tif (deflated 10%)
  adding: RH200/DJF 2007.tif (deflated 9%)
  adding: RH200/MAM 2008.tif (deflated 9%)
  adding: RH200/DJF 2012.tif (deflated 9%)
  adding: RH200/JJA 2015.tif (deflated 9%)
  adding: RH200/MAM 2023.tif (deflated 10%)
  adding: RH200/JJA 2011.tif (deflated 10%)
  adding: RH200/MAM 2007.tif (deflated 9%)
  adding: RH200/JJA 2002.tif (deflated 9%)
  adding: RH200/MAM 2018.tif (deflated 9%)
  adding: RH200/DJF 2004.tif (deflated 10%)
  adding: RH200/SON 1997.tif (deflated 9%)
  adding: RH200/SON 2013.tif (deflated 10%)
  adding: RH200/SON 2010.tif (deflated 9%)
  adding: RH200/JJA 2014.tif (deflated 10%)
  adding: RH200/JJA 2017.tif (deflated 10%)
  adding: RH200/JJA 2008.tif (deflated 9%)
  adding: RH200/SON 2021.tif (deflated 9%)
  adding: RH200/DJF 2009.tif (deflated 9%)
  adding: RH200/MAM 2010.tif (deflated 9%)
  adding: RH200/JJA 2004.tif (deflated 10%)
  adding: RH200/SON 2009.tif (deflated 10%)
  adding: RH200/MAM 2005.tif (deflated 9%)
  adding: RH200/SON 2019.tif (deflated 9%)
  adding: RH200/JJA 1992.tif (deflated 9%)
  adding: RH200/DJF 1994.tif (deflated 10%)
  adding: RH200/JJA 2021.tif (deflated 9%)
  adding: RH200/JJA 1994.tif (deflated 9%)
  adding: RH200/MAM 1992.tif (deflated 9%)
  adding: RH200/MAM 1999.tif (deflated 9%)
  adding: RH200/SON 1991.tif (deflated 10%)
  adding: RH200/MAM 2015.tif (deflated 10%)
  adding: RH200/MAM 2016.tif (deflated 10%)
  adding: RH200/JJA 2019.tif (deflated 10%)
  adding: RH200/SON 1999.tif (deflated 10%)
  adding: RH200/SON 2018.tif (deflated 10%)
  adding: RH200/MAM 2019.tif (deflated 10%)
  adding: RH200/MAM 2011.tif (deflated 9%)
  adding: RH200/JJA 2013.tif (deflated 10%)
  adding: RH200/SON 2001.tif (deflated 9%)
  adding: RH200/MAM 1993.tif (deflated 9%)
  adding: RH200/SON 2003.tif (deflated 10%)
  adding: RH200/DJF 2016.tif (deflated 9%)
  adding: RH200/SON 2011.tif (deflated 9%)
  adding: RH200/MAM 2013.tif (deflated 9%)
  adding: RH200/DJF 1992.tif (deflated 9%)
  adding: RH200/DJF 1993.tif (deflated 9%)
  adding: RH200/SON 1998.tif (deflated 10%)
  adding: RH200/SON 2022.tif (deflated 10%)
  adding: RH200/DJF 1998.tif (deflated 9%)
  adding: RH200/MAM 1997.tif (deflated 9%)
  adding: RH200/SON 2023.tif (deflated 9%)
  adding: RH200/DJF 2001.tif (deflated 9%)
  adding: RH200/JJA 2010.tif (deflated 9%)
  adding: RH200/DJF 2024.tif (deflated 9%)
  adding: RH200/SON 1994.tif (deflated 10%)
  adding: RH200/MAM 2020.tif (deflated 9%)
  adding: RH200/JJA 1996.tif (deflated 10%)
  adding: RH200/SON 2017.tif (deflated 10%)
  adding: RH200/MAM 1995.tif (deflated 9%)
  adding: RH200/SON 2004.tif (deflated 10%)
  adding: RH200/DJF 2017.tif (deflated 9%)
  adding: RH200/JJA 2000.tif (deflated 10%)
  adding: RH200/DJF 2005.tif (deflated 9%)
  adding: RH200/MAM 1996.tif (deflated 9%)
  adding: RH200/SON 2012.tif (deflated 10%)
  adding: RH200/SON 1995.tif (deflated 10%)
  adding: RH200/MAM 2000.tif (deflated 9%)
  adding: RH200/SON 2014.tif (deflated 10%)
  adding: RH200/MAM 2014.tif (deflated 10%)
  adding: RH200/MAM 2022.tif (deflated 9%)
  adding: RH200/DJF 2014.tif (deflated 9%)
  adding: RH200/DJF 1991.tif (deflated 9%)
  adding: RH200/JJA 2003.tif (deflated 10%)
  adding: RH200/DJF 2013.tif (deflated 9%)
  adding: RH200/MAM 1991.tif (deflated 9%)
  adding: RH200/DJF 2021.tif (deflated 9%)
  adding: RH200/SON 2007.tif (deflated 10%)
  adding: RH200/MAM 2001.tif (deflated 10%)
  adding: RH200/JJA 2001.tif (deflated 10%)
  adding: RH200/SON 2015.tif (deflated 10%)
  adding: RH200/DJF 2006.tif (deflated 9%)
  adding: RH200/JJA 2012.tif (deflated 9%)
  adding: RH200/SON 2016.tif (deflated 10%)
  adding: RH200/MAM 2021.tif (deflated 10%)
  adding: RH200/DJF 1996.tif (deflated 9%)
  adding: RH200/JJA 2020.tif (deflated 10%)
  adding: RH200/JJA 1998.tif (deflated 10%)
  adding: RH200/MAM 2024.tif (deflated 9%)
  adding: RH850/ (stored 0%)
  adding: RH850/SON 2005.tif (deflated 11%)
  adding: RH850/DJF 2019.tif (deflated 10%)
  adding: RH850/MAM 2017.tif (deflated 10%)
  adding: RH850/SON 2008.tif (deflated 10%)
  adding: RH850/DJF 1995.tif (deflated 10%)
  adding: RH850/DJF 2015.tif (deflated 10%)
  adding: RH850/DJF 2000.tif (deflated 10%)
  adding: RH850/SON 1992.tif (deflated 10%)
  adding: RH850/JJA 2018.tif (deflated 11%)
  adding: RH850/SON 2000.tif (deflated 10%)
  adding: RH850/JJA 2022.tif (deflated 10%)
  adding: RH850/JJA 2006.tif (deflated 11%)
  adding: RH850/MAM 2004.tif (deflated 10%)
  adding: RH850/JJA 2023.tif (deflated 11%)
  adding: RH850/MAM 2006.tif (deflated 10%)
  adding: RH850/DJF 2010.tif (deflated 9%)
  adding: RH850/MAM 2003.tif (deflated 10%)
  adding: RH850/SON 2020.tif (deflated 10%)
  adding: RH850/JJA 1993.tif (deflated 10%)
  adding: RH850/MAM 2002.tif (deflated 10%)
  adding: RH850/JJA 2007.tif (deflated 11%)
  adding: RH850/DJF 2022.tif (deflated 10%)
  adding: RH850/JJA 2005.tif (deflated 11%)
  adding: RH850/SON 1993.tif (deflated 10%)
  adding: RH850/MAM 1994.tif (deflated 10%)
  adding: RH850/SON 2006.tif (deflated 11%)
  adding: RH850/JJA 1997.tif (deflated 10%)
  adding: RH850/MAM 2009.tif (deflated 10%)
  adding: RH850/DJF 2002.tif (deflated 10%)
  adding: RH850/JJA 1995.tif (deflated 11%)
  adding: RH850/DJF 2023.tif (deflated 10%)
  adding: RH850/DJF 1997.tif (deflated 10%)
  adding: RH850/JJA 2024.tif (deflated 10%)
  adding: RH850/JJA 2016.tif (deflated 11%)
  adding: RH850/JJA 1999.tif (deflated 11%)
  adding: RH850/DJF 2011.tif (deflated 10%)
  adding: RH850/DJF 2003.tif (deflated 10%)
  adding: RH850/DJF 1999.tif (deflated 10%)
  adding: RH850/JJA 2009.tif (deflated 11%)
  adding: RH850/SON 1996.tif (deflated 10%)
  adding: RH850/MAM 1998.tif (deflated 10%)
  adding: RH850/DJF 2008.tif (deflated 10%)
  adding: RH850/DJF 2018.tif (deflated 9%)
  adding: RH850/SON 2002.tif (deflated 11%)
  adding: RH850/MAM 2012.tif (deflated 10%)
  adding: RH850/DJF 2025.tif (deflated 9%)
  adding: RH850/DJF 2020.tif (deflated 9%)
  adding: RH850/SON 2024.tif (deflated 10%)
  adding: RH850/JJA 1991.tif (deflated 11%)
  adding: RH850/DJF 2007.tif (deflated 10%)
  adding: RH850/MAM 2008.tif (deflated 10%)
  adding: RH850/DJF 2012.tif (deflated 9%)
  adding: RH850/JJA 2015.tif (deflated 11%)
  adding: RH850/MAM 2023.tif (deflated 10%)
  adding: RH850/JJA 2011.tif (deflated 11%)
  adding: RH850/MAM 2007.tif (deflated 10%)
  adding: RH850/JJA 2002.tif (deflated 11%)
  adding: RH850/MAM 2018.tif (deflated 10%)
  adding: RH850/DJF 2004.tif (deflated 10%)
  adding: RH850/SON 1997.tif (deflated 10%)
  adding: RH850/SON 2013.tif (deflated 11%)
  adding: RH850/SON 2010.tif (deflated 10%)
  adding: RH850/JJA 2014.tif (deflated 11%)
  adding: RH850/JJA 2017.tif (deflated 11%)
  adding: RH850/JJA 2008.tif (deflated 11%)
  adding: RH850/SON 2021.tif (deflated 10%)
  adding: RH850/DJF 2009.tif (deflated 9%)
  adding: RH850/MAM 2010.tif (deflated 10%)
  adding: RH850/JJA 2004.tif (deflated 11%)
  adding: RH850/SON 2009.tif (deflated 11%)
  adding: RH850/MAM 2005.tif (deflated 10%)
  adding: RH850/SON 2019.tif (deflated 10%)
  adding: RH850/JJA 1992.tif (deflated 10%)
  adding: RH850/DJF 1994.tif (deflated 10%)
  adding: RH850/JJA 2021.tif (deflated 10%)
  adding: RH850/JJA 1994.tif (deflated 10%)
  adding: RH850/MAM 1992.tif (deflated 10%)
  adding: RH850/MAM 1999.tif (deflated 10%)
  adding: RH850/SON 1991.tif (deflated 11%)
  adding: RH850/MAM 2015.tif (deflated 10%)
  adding: RH850/MAM 2016.tif (deflated 10%)
  adding: RH850/JJA 2019.tif (deflated 11%)
  adding: RH850/SON 1999.tif (deflated 10%)
  adding: RH850/SON 2018.tif (deflated 11%)
  adding: RH850/MAM 2019.tif (deflated 10%)
  adding: RH850/MAM 2011.tif (deflated 10%)
  adding: RH850/JJA 2013.tif (deflated 11%)
  adding: RH850/SON 2001.tif (deflated 10%)
  adding: RH850/MAM 1993.tif (deflated 10%)
  adding: RH850/SON 2003.tif (deflated 11%)
  adding: RH850/DJF 2016.tif (deflated 9%)
  adding: RH850/SON 2011.tif (deflated 10%)
  adding: RH850/MAM 2013.tif (deflated 10%)
  adding: RH850/DJF 1992.tif (deflated 9%)
  adding: RH850/DJF 1993.tif (deflated 9%)
  adding: RH850/SON 1998.tif (deflated 10%)
  adding: RH850/SON 2022.tif (deflated 10%)
  adding: RH850/DJF 1998.tif (deflated 9%)
  adding: RH850/MAM 1997.tif (deflated 10%)
  adding: RH850/SON 2023.tif (deflated 10%)
  adding: RH850/DJF 2001.tif (deflated 10%)
  adding: RH850/JJA 2010.tif (deflated 10%)
  adding: RH850/DJF 2024.tif (deflated 10%)
  adding: RH850/SON 1994.tif (deflated 10%)
  adding: RH850/MAM 2020.tif (deflated 10%)
  adding: RH850/JJA 1996.tif (deflated 10%)
  adding: RH850/SON 2017.tif (deflated 10%)
  adding: RH850/MAM 1995.tif (deflated 10%)
  adding: RH850/SON 2004.tif (deflated 11%)
  adding: RH850/DJF 2017.tif (deflated 10%)
  adding: RH850/JJA 2000.tif (deflated 11%)
  adding: RH850/DJF 2005.tif (deflated 10%)
  adding: RH850/MAM 1996.tif (deflated 10%)
  adding: RH850/SON 2012.tif (deflated 11%)
  adding: RH850/SON 1995.tif (deflated 10%)
  adding: RH850/MAM 2000.tif (deflated 10%)
  adding: RH850/SON 2014.tif (deflated 11%)
  adding: RH850/MAM 2014.tif (deflated 10%)
  adding: RH850/MAM 2022.tif (deflated 10%)
  adding: RH850/DJF 2014.tif (deflated 9%)
  adding: RH850/DJF 1991.tif (deflated 9%)
  adding: RH850/JJA 2003.tif (deflated 11%)
  adding: RH850/DJF 2013.tif (deflated 10%)
  adding: RH850/MAM 1991.tif (deflated 10%)
  adding: RH850/DJF 2021.tif (deflated 9%)
  adding: RH850/SON 2007.tif (deflated 10%)
  adding: RH850/MAM 2001.tif (deflated 10%)
  adding: RH850/JJA 2001.tif (deflated 11%)
  adding: RH850/SON 2015.tif (deflated 11%)
  adding: RH850/DJF 2006.tif (deflated 9%)
  adding: RH850/JJA 2012.tif (deflated 10%)
  adding: RH850/SON 2016.tif (deflated 10%)
  adding: RH850/MAM 2021.tif (deflated 10%)
  adding: RH850/DJF 1996.tif (deflated 9%)
  adding: RH850/JJA 2020.tif (deflated 11%)
  adding: RH850/JJA 1998.tif (deflated 11%)
  adding: RH850/MAM 2024.tif (deflated 10%)
  adding: GPH200/ (stored 0%)
  adding: GPH200/SON 2005.tif (deflated 23%)
  adding: GPH200/DJF 2019.tif (deflated 19%)
  adding: GPH200/MAM 2017.tif (deflated 21%)
  adding: GPH200/SON 2008.tif (deflated 22%)
  adding: GPH200/DJF 1995.tif (deflated 19%)
  adding: GPH200/DJF 2015.tif (deflated 19%)
  adding: GPH200/DJF 2000.tif (deflated 18%)
  adding: GPH200/SON 1992.tif (deflated 21%)
  adding: GPH200/JJA 2018.tif (deflated 22%)
  adding: GPH200/SON 2000.tif (deflated 22%)
  adding: GPH200/JJA 2022.tif (deflated 22%)
  adding: GPH200/JJA 2006.tif (deflated 22%)
  adding: GPH200/MAM 2004.tif (deflated 21%)
  adding: GPH200/JJA 2023.tif (deflated 23%)
  adding: GPH200/MAM 2006.tif (deflated 21%)
  adding: GPH200/DJF 2010.tif (deflated 18%)
  adding: GPH200/MAM 2003.tif (deflated 21%)
  adding: GPH200/SON 2020.tif (deflated 22%)
  adding: GPH200/JJA 1993.tif (deflated 22%)
  adding: GPH200/MAM 2002.tif (deflated 20%)
  adding: GPH200/JJA 2007.tif (deflated 22%)
  adding: GPH200/DJF 2022.tif (deflated 19%)
  adding: GPH200/JJA 2005.tif (deflated 22%)
  adding: GPH200/SON 1993.tif (deflated 21%)
  adding: GPH200/MAM 1994.tif (deflated 21%)
  adding: GPH200/SON 2006.tif (deflated 22%)
  adding: GPH200/JJA 1997.tif (deflated 22%)
  adding: GPH200/MAM 2009.tif (deflated 21%)
  adding: GPH200/DJF 2002.tif (deflated 19%)
  adding: GPH200/JJA 1995.tif (deflated 22%)
  adding: GPH200/DJF 2023.tif (deflated 19%)
  adding: GPH200/DJF 1997.tif (deflated 19%)
  adding: GPH200/JJA 2024.tif (deflated 22%)
  adding: GPH200/JJA 2016.tif (deflated 22%)
  adding: GPH200/JJA 1999.tif (deflated 22%)
  adding: GPH200/DJF 2011.tif (deflated 19%)
  adding: GPH200/DJF 2003.tif (deflated 19%)
  adding: GPH200/DJF 1999.tif (deflated 19%)
  adding: GPH200/JJA 2009.tif (deflated 22%)
  adding: GPH200/SON 1996.tif (deflated 22%)
  adding: GPH200/MAM 1998.tif (deflated 21%)
  adding: GPH200/DJF 2008.tif (deflated 19%)
  adding: GPH200/DJF 2018.tif (deflated 18%)
  adding: GPH200/SON 2002.tif (deflated 21%)
  adding: GPH200/MAM 2012.tif (deflated 21%)
  adding: GPH200/DJF 2025.tif (deflated 19%)
  adding: GPH200/DJF 2020.tif (deflated 19%)
  adding: GPH200/SON 2024.tif (deflated 22%)
  adding: GPH200/JJA 1991.tif (deflated 23%)
  adding: GPH200/DJF 2007.tif (deflated 19%)
  adding: GPH200/MAM 2008.tif (deflated 20%)
  adding: GPH200/DJF 2012.tif (deflated 18%)
  adding: GPH200/JJA 2015.tif (deflated 22%)
  adding: GPH200/MAM 2023.tif (deflated 20%)
  adding: GPH200/JJA 2011.tif (deflated 23%)
  adding: GPH200/MAM 2007.tif (deflated 21%)
  adding: GPH200/JJA 2002.tif (deflated 22%)
  adding: GPH200/MAM 2018.tif (deflated 20%)
  adding: GPH200/DJF 2004.tif (deflated 19%)
  adding: GPH200/SON 1997.tif (deflated 21%)
  adding: GPH200/SON 2013.tif (deflated 23%)
  adding: GPH200/SON 2010.tif (deflated 21%)
  adding: GPH200/JJA 2014.tif (deflated 22%)
  adding: GPH200/JJA 2017.tif (deflated 23%)
  adding: GPH200/JJA 2008.tif (deflated 22%)
  adding: GPH200/SON 2021.tif (deflated 22%)
  adding: GPH200/DJF 2009.tif (deflated 19%)
  adding: GPH200/MAM 2010.tif (deflated 20%)
  adding: GPH200/JJA 2004.tif (deflated 23%)
  adding: GPH200/SON 2009.tif (deflated 22%)
  adding: GPH200/MAM 2005.tif (deflated 20%)
  adding: GPH200/SON 2019.tif (deflated 21%)
  adding: GPH200/JJA 1992.tif (deflated 22%)
  adding: GPH200/DJF 1994.tif (deflated 19%)
  adding: GPH200/JJA 2021.tif (deflated 23%)
  adding: GPH200/JJA 1994.tif (deflated 22%)
  adding: GPH200/MAM 1992.tif (deflated 20%)
  adding: GPH200/MAM 1999.tif (deflated 21%)
  adding: GPH200/SON 1991.tif (deflated 22%)
  adding: GPH200/MAM 2015.tif (deflated 21%)
  adding: GPH200/MAM 2016.tif (deflated 21%)
  adding: GPH200/JJA 2019.tif (deflated 22%)
  adding: GPH200/SON 1999.tif (deflated 22%)
  adding: GPH200/SON 2018.tif (deflated 21%)
  adding: GPH200/MAM 2019.tif (deflated 21%)
  adding: GPH200/MAM 2011.tif (deflated 20%)
  adding: GPH200/JJA 2013.tif (deflated 22%)
  adding: GPH200/SON 2001.tif (deflated 22%)
  adding: GPH200/MAM 1993.tif (deflated 21%)
  adding: GPH200/SON 2003.tif (deflated 22%)
  adding: GPH200/DJF 2016.tif (deflated 18%)
  adding: GPH200/SON 2011.tif (deflated 22%)
  adding: GPH200/MAM 2013.tif (deflated 20%)
  adding: GPH200/DJF 1992.tif (deflated 18%)
  adding: GPH200/DJF 1993.tif (deflated 19%)
  adding: GPH200/SON 1998.tif (deflated 22%)
  adding: GPH200/SON 2022.tif (deflated 22%)
  adding: GPH200/DJF 1998.tif (deflated 19%)
  adding: GPH200/MAM 1997.tif (deflated 20%)
  adding: GPH200/SON 2023.tif (deflated 22%)
  adding: GPH200/DJF 2001.tif (deflated 19%)
  adding: GPH200/JJA 2010.tif (deflated 22%)
  adding: GPH200/DJF 2024.tif (deflated 18%)
  adding: GPH200/SON 1994.tif (deflated 22%)

  adding: GPH200/MAM 2020.tif (deflated 21%)
  adding: GPH200/JJA 1996.tif (deflated 22%)
  adding: GPH200/SON 2017.tif (deflated 22%)
  adding: GPH200/MAM 1995.tif (deflated 20%)
  adding: GPH200/SON 2004.tif (deflated 22%)
  adding: GPH200/DJF 2017.tif (deflated 18%)
  adding: GPH200/JJA 2000.tif (deflated 22%)
  adding: GPH200/DJF 2005.tif (deflated 18%)
  adding: GPH200/MAM 1996.tif (deflated 21%)
  adding: GPH200/SON 2012.tif (deflated 21%)
  adding: GPH200/SON 1995.tif (deflated 22%)
  adding: GPH200/MAM 2000.tif (deflated 20%)
  adding: GPH200/SON 2014.tif (deflated 22%)
  adding: GPH200/MAM 2014.tif (deflated 21%)
  adding: GPH200/MAM 2022.tif (deflated 21%)
  adding: GPH200/DJF 2014.tif (deflated 19%)
  adding: GPH200/DJF 1991.tif (deflated 19%)
  adding: GPH200/JJA 2003.tif (deflated 22%)
  adding: GPH200/DJF 2013.tif (deflated 19%)
  adding: GPH200/MAM 1991.tif (deflated 21%)
  adding: GPH200/DJF 2021.tif (deflated 18%)
  adding: GPH200/SON 2007.tif (deflated 22%)
  adding: GPH200/MAM 2001.tif (deflated 21%)
  adding: GPH200/JJA 2001.tif (deflated 22%)
  adding: GPH200/SON 2015.tif (deflated 22%)
  adding: GPH200/DJF 2006.tif (deflated 19%)
  adding: GPH200/JJA 2012.tif (deflated 21%)
  adding: GPH200/SON 2016.tif (deflated 21%)
  adding: GPH200/MAM 2021.tif (deflated 21%)
  adding: GPH200/DJF 1996.tif (deflated 19%)
  adding: GPH200/JJA 2020.tif (deflated 22%)
  adding: GPH200/JJA 1998.tif (deflated 22%)
  adding: GPH200/MAM 2024.tif (deflated 20%)
  adding: Wind200/ (stored 0%)
  adding: Wind200/SON 2005.tif (deflated 9%)
  adding: Wind200/DJF 2019.tif (deflated 8%)
  adding: Wind200/MAM 2017.tif (deflated 8%)
  adding: Wind200/SON 2008.tif (deflated 9%)
  adding: Wind200/DJF 1995.tif (deflated 8%)
  adding: Wind200/DJF 2015.tif (deflated 8%)
  adding: Wind200/DJF 2000.tif (deflated 8%)
  adding: Wind200/SON 1992.tif (deflated 9%)
  adding: Wind200/JJA 2018.tif (deflated 8%)
  adding: Wind200/SON 2000.tif (deflated 9%)
  adding: Wind200/JJA 2022.tif (deflated 8%)
  adding: Wind200/JJA 2006.tif (deflated 9%)
  adding: Wind200/MAM 2004.tif (deflated 8%)
  adding: Wind200/JJA 2023.tif (deflated 8%)
  adding: Wind200/MAM 2006.tif (deflated 8%)
  adding: Wind200/DJF 2010.tif (deflated 8%)
  adding: Wind200/MAM 2003.tif (deflated 8%)
  adding: Wind200/SON 2020.tif (deflated 9%)
  adding: Wind200/JJA 1993.tif (deflated 8%)
  adding: Wind200/MAM 2002.tif (deflated 8%)
  adding: Wind200/JJA 2007.tif (deflated 8%)
  adding: Wind200/DJF 2022.tif (deflated 8%)
  adding: Wind200/JJA 2005.tif (deflated 9%)
  adding: Wind200/SON 1993.tif (deflated 9%)
  adding: Wind200/MAM 1994.tif (deflated 9%)
  adding: Wind200/SON 2006.tif (deflated 9%)
  adding: Wind200/JJA 1997.tif (deflated 8%)
  adding: Wind200/MAM 2009.tif (deflated 8%)
  adding: Wind200/DJF 2002.tif (deflated 8%)
  adding: Wind200/JJA 1995.tif (deflated 8%)
  adding: Wind200/DJF 2023.tif (deflated 8%)
  adding: Wind200/DJF 1997.tif (deflated 8%)
  adding: Wind200/JJA 2024.tif (deflated 8%)
  adding: Wind200/JJA 2016.tif (deflated 8%)
  adding: Wind200/JJA 1999.tif (deflated 8%)
  adding: Wind200/DJF 2011.tif (deflated 8%)
  adding: Wind200/DJF 2003.tif (deflated 8%)
  adding: Wind200/DJF 1999.tif (deflated 8%)
  adding: Wind200/JJA 2009.tif (deflated 8%)
  adding: Wind200/SON 1996.tif (deflated 9%)
  adding: Wind200/MAM 1998.tif (deflated 9%)
  adding: Wind200/DJF 2008.tif (deflated 8%)
  adding: Wind200/DJF 2018.tif (deflated 8%)
  adding: Wind200/SON 2002.tif (deflated 9%)
  adding: Wind200/MAM 2012.tif (deflated 9%)
  adding: Wind200/DJF 2025.tif (deflated 8%)
  adding: Wind200/DJF 2020.tif (deflated 8%)
  adding: Wind200/SON 2024.tif (deflated 9%)
  adding: Wind200/JJA 1991.tif (deflated 9%)
  adding: Wind200/DJF 2007.tif (deflated 8%)
  adding: Wind200/MAM 2008.tif (deflated 8%)
  adding: Wind200/DJF 2012.tif (deflated 8%)
  adding: Wind200/JJA 2015.tif (deflated 8%)
  adding: Wind200/MAM 2023.tif (deflated 8%)
  adding: Wind200/JJA 2011.tif (deflated 8%)
  adding: Wind200/MAM 2007.tif (deflated 8%)
  adding: Wind200/JJA 2002.tif (deflated 8%)
  adding: Wind200/MAM 2018.tif (deflated 8%)
  adding: Wind200/DJF 2004.tif (deflated 8%)
  adding: Wind200/SON 1997.tif (deflated 8%)
  adding: Wind200/SON 2013.tif (deflated 9%)
  adding: Wind200/SON 2010.tif (deflated 9%)
  adding: Wind200/JJA 2014.tif (deflated 9%)
  adding: Wind200/JJA 2017.tif (deflated 8%)
  adding: Wind200/JJA 2008.tif (deflated 8%)
  adding: Wind200/SON 2021.tif (deflated 9%)
  adding: Wind200/DJF 2009.tif (deflated 8%)
  adding: Wind200/MAM 2010.tif (deflated 8%)
  adding: Wind200/JJA 2004.tif (deflated 9%)
  adding: Wind200/SON 2009.tif (deflated 9%)
  adding: Wind200/MAM 2005.tif (deflated 8%)
  adding: Wind200/SON 2019.tif (deflated 9%)
  adding: Wind200/JJA 1992.tif (deflated 8%)
  adding: Wind200/DJF 1994.tif (deflated 8%)
  adding: Wind200/JJA 2021.tif (deflated 8%)
  adding: Wind200/JJA 1994.tif (deflated 8%)
  adding: Wind200/MAM 1992.tif (deflated 8%)
  adding: Wind200/MAM 1999.tif (deflated 9%)
  adding: Wind200/SON 1991.tif (deflated 9%)
  adding: Wind200/MAM 2015.tif (deflated 8%)
  adding: Wind200/MAM 2016.tif (deflated 9%)
  adding: Wind200/JJA 2019.tif (deflated 8%)
  adding: Wind200/SON 1999.tif (deflated 9%)
  adding: Wind200/SON 2018.tif (deflated 9%)
  adding: Wind200/MAM 2019.tif (deflated 8%)
  adding: Wind200/MAM 2011.tif (deflated 8%)
  adding: Wind200/JJA 2013.tif (deflated 8%)
  adding: Wind200/SON 2001.tif (deflated 9%)
  adding: Wind200/MAM 1993.tif (deflated 8%)
  adding: Wind200/SON 2003.tif (deflated 9%)
  adding: Wind200/DJF 2016.tif (deflated 8%)
  adding: Wind200/SON 2011.tif (deflated 8%)
  adding: Wind200/MAM 2013.tif (deflated 8%)
  adding: Wind200/DJF 1992.tif (deflated 8%)
  adding: Wind200/DJF 1993.tif (deflated 8%)
  adding: Wind200/SON 1998.tif (deflated 9%)
  adding: Wind200/SON 2022.tif (deflated 9%)
  adding: Wind200/DJF 1998.tif (deflated 8%)
  adding: Wind200/MAM 1997.tif (deflated 8%)
  adding: Wind200/SON 2023.tif (deflated 8%)
  adding: Wind200/DJF 2001.tif (deflated 8%)
  adding: Wind200/JJA 2010.tif (deflated 8%)
  adding: Wind200/DJF 2024.tif (deflated 8%)
  adding: Wind200/SON 1994.tif (deflated 9%)
  adding: Wind200/MAM 2020.tif (deflated 9%)
  adding: Wind200/JJA 1996.tif (deflated 9%)
  adding: Wind200/SON 2017.tif (deflated 9%)
  adding: Wind200/MAM 1995.tif (deflated 8%)
  adding: Wind200/SON 2004.tif (deflated 9%)
  adding: Wind200/DJF 2017.tif (deflated 8%)
  adding: Wind200/JJA 2000.tif (deflated 8%)
  adding: Wind200/DJF 2005.tif (deflated 8%)
  adding: Wind200/MAM 1996.tif (deflated 8%)
  adding: Wind200/SON 2012.tif (deflated 9%)
  adding: Wind200/SON 1995.tif (deflated 9%)
  adding: Wind200/MAM 2000.tif (deflated 8%)
  adding: Wind200/SON 2014.tif (deflated 9%)
  adding: Wind200/MAM 2014.tif (deflated 9%)
  adding: Wind200/MAM 2022.tif (deflated 8%)
  adding: Wind200/DJF 2014.tif (deflated 8%)
  adding: Wind200/DJF 1991.tif (deflated 8%)
  adding: Wind200/JJA 2003.tif (deflated 8%)
  adding: Wind200/DJF 2013.tif (deflated 8%)
  adding: Wind200/MAM 1991.tif (deflated 8%)
  adding: Wind200/DJF 2021.tif (deflated 8%)
  adding: Wind200/SON 2007.tif (deflated 9%)
  adding: Wind200/MAM 2001.tif (deflated 8%)
  adding: Wind200/JJA 2001.tif (deflated 9%)
  adding: Wind200/SON 2015.tif (deflated 9%)
  adding: Wind200/DJF 2006.tif (deflated 8%)
  adding: Wind200/JJA 2012.tif (deflated 8%)
  adding: Wind200/SON 2016.tif (deflated 9%)
  adding: Wind200/MAM 2021.tif (deflated 8%)
  adding: Wind200/DJF 1996.tif (deflated 8%)
  adding: Wind200/JJA 2020.tif (deflated 9%)
  adding: Wind200/JJA 1998.tif (deflated 8%)
  adding: Wind200/MAM 2024.tif (deflated 8%)

**Read NC data**

In [2]:
# Load dataset
dw = xr.open_dataset('data/cape_80N20S50W80E.nc', engine="netcdf4")  # Load NetCDF file
#dw = dw.sel(latitude=slice(45, 15))
#dw = dw.sel(valid_time=slice('1991-01-01', None))

In [3]:
dw

<xarray.Dataset>
Dimensions:     (valid_time: 408, latitude: 401, longitude: 521)
Coordinates:
    number      int64 ...
  * valid_time  (valid_time) datetime64[ns] 1991-01-01 1991-02-01 ... 2024-12-01
  * latitude    (latitude) float64 80.0 79.75 79.5 79.25 ... -19.5 -19.75 -20.0
  * longitude   (longitude) float64 -50.0 -49.75 -49.5 ... 79.5 79.75 80.0
    expver      (valid_time) object ...
Data variables:
    cape        (valid_time, latitude, longitude) float32 ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts

**Seasonal Relative Humidity anomalies**

In [3]:
# Convert 'date' from integer to datetime format
dw = dw.assign_coords(date=pd.to_datetime(dw['valid_time'].data.astype(str), format='ISO8601'))

# Convert dataset to DataFrame
df = dw['cape'].to_dataframe().reset_index()

# Extract year and month
df = df.drop('expver', axis=1)
df = df.drop('number', axis=1)
df['year'] = df['valid_time'].dt.year
df['month'] = df['valid_time'].dt.month

# **FAST NumPy Vectorized Method for Assigning Seasons**
seasons = np.array(["DJF", "MAM", "JJA", "SON"])

# Define conditions for season assignment
winter = df['month'].isin([12, 1, 2])
spring = df['month'].isin([3, 4, 5])
summer = df['month'].isin([6, 7, 8])
autumn = df['month'].isin([9, 10, 11])

# Assign seasons using np.select (much faster than apply)
df['season'] = np.select([winter, spring, summer, autumn], seasons)

# Assign season_year (December belongs to next year’s winter)
df['season_year'] = df['year']
df.loc[df['month'] == 12, 'season_year'] += 1  # Shift December to next year's winter

# **STEP 1: Compute Actual Seasonal SST (For Each Year)**
seasonal_cape_df = df.groupby(['latitude', 'longitude', 'season_year', 'season'])['cape'].mean().reset_index()

# **STEP 2: Compute Seasonal Climatology (Long-Term Average Over All Years)**
# Filter to only include seasons from 1991 to 2020 (30 years period recommended by the WMO)
filtered_df = seasonal_cape_df[(seasonal_cape_df['season_year'] >= 1991) & (seasonal_cape_df['season_year'] <= 2020)]

seasonal_climatology_df = filtered_df.groupby(['latitude', 'longitude', 'season'])['cape'].mean().reset_index()
seasonal_climatology_df.rename(columns={'cape': 'cape_climatology'}, inplace=True)

# **STEP 3: Merge Actual SST With Climatology**
mergedf = pd.merge(seasonal_cape_df, seasonal_climatology_df, on=['latitude', 'longitude', 'season'], how="left")
# **STEP 4: Compute Seasonal Anomalies**
mergedf['cape_anomaly'] = mergedf['cape'] - mergedf['cape_climatology']

mergedf['date'] = (
    mergedf['season'].astype(str) 
    + ' ' 
    + mergedf['season_year'].astype(str)
)
mergedf

,latitude,longitude,season_year,season,cape,cape_climatology,cape_anomaly,date
0,-20.0,-50.0,1991,DJF,956.250000,1004.585083,-48.335083,DJF 1991
1,-20.0,-50.0,1991,JJA,18.208334,28.422222,-10.213888,JJA 1991
2,-20.0,-50.0,1991,MAM,472.875000,469.984009,2.890991,MAM 1991
3,-20.0,-50.0,1991,SON,409.229156,413.361816,-4.132660,SON 1991
4,-20.0,-50.0,1992,DJF,954.708313,1004.585083,-49.876770,DJF 1992
...,...,...,...,...,...,...,...,...
28622172,80.0,80.0,2024,DJF,1.645833,1.728472,-0.082639,DJF 2024
28622173,80.0,80.0,2024,JJA,4.833333,6.294444,-1.461111,JJA 2024
28622174,80.0,80.0,2024,MAM,2.083333,2.415972,-0.332639,MAM 2024
28622175,80.0,80.0,2024,SON,6.333333,5.166667,1.166667,SON 2024
28622176,80.0,80.0,2025,DJF,1.500000,1.728472,-0.228472,DJF 2025

**Apply Welch’s T-Test**

In [4]:
from scipy.stats import ttest_ind

# Define drought years
drought_years = [1994, 1995, 1999, 2000, 2001, 2005, 2016, 2019, 2020, 2021, 2022, 2023]  # Replace with your own

# Create a unique season key
#mergedf['season_key'] = mergedf['season'] + '_' + mergedf['season_year'].astype(str)

# Create a multi-index pivot: rows = (season_year), columns = (lat, lon, season), values = anomaly
pivot = mergedf.pivot_table(
    index='season_year',
    columns=['latitude', 'longitude', 'season'],
    values='cape_anomaly'
)

# Get drought and non-drought subsets
drought_vals = pivot.loc[pivot.index.isin(drought_years)]
non_drought_vals = pivot.loc[~pivot.index.isin(drought_years)]

# Apply Welch's t-test column-wise
t_vals, p_vals = ttest_ind(
    drought_vals, non_drought_vals,
    axis=0, equal_var=False, nan_policy='omit'
)

# Convert result arrays to DataFrames with same multi-index columns
#t_df = pd.DataFrame([t_vals], columns=pivot.columns).T.reset_index()
p_df = pd.DataFrame([p_vals], columns=pivot.columns).T.reset_index()
#t_df.columns = ['latitude', 'longitude', 'season', 't_value']
p_df.columns = ['latitude', 'longitude', 'season', 'p_value']

# Merge t/p values back
#significance_df = pd.merge(t_df, p_df, on=['latitude', 'longitude', 'season'])

# Merge with original mergedf
mergedf = pd.merge(mergedf, p_df, on=['latitude', 'longitude', 'season'], how='left')
mergedf

,latitude,longitude,season_year,season,cape,cape_climatology,cape_anomaly,date,p_value
0,-20.0,-50.0,1991,DJF,956.250000,1004.585083,-48.335083,DJF 1991,0.744111
1,-20.0,-50.0,1991,JJA,18.208334,28.422222,-10.213888,JJA 1991,0.431973
2,-20.0,-50.0,1991,MAM,472.875000,469.984009,2.890991,MAM 1991,0.066592
3,-20.0,-50.0,1991,SON,409.229156,413.361816,-4.132660,SON 1991,0.182400
4,-20.0,-50.0,1992,DJF,954.708313,1004.585083,-49.876770,DJF 1992,0.744111
...,...,...,...,...,...,...,...,...,...
28622172,80.0,80.0,2024,DJF,1.645833,1.728472,-0.082639,DJF 2024,0.870356
28622173,80.0,80.0,2024,JJA,4.833333,6.294444,-1.461111,JJA 2024,0.477138
28622174,80.0,80.0,2024,MAM,2.083333,2.415972,-0.332639,MAM 2024,0.805538
28622175,80.0,80.0,2024,SON,6.333333,5.166667,1.166667,SON 2024,0.968994
28622176,80.0,80.0,2025,DJF,1.500000,1.728472,-0.228472,DJF 2025,0.870356

In [5]:
# Convert back to xarray
anomalies = mergedf.set_index(['date', 'latitude', 'longitude'])['cape_anomaly'].to_xarray()
pval = mergedf.set_index(['date', 'latitude', 'longitude'])['p_value'].to_xarray()
anomalies

<xarray.DataArray 'cape_anomaly' (date: 137, latitude: 401, longitude: 521)>
array([[[-4.83350830e+01, -2.21736450e+01,  5.74060059e+00, ...,
         -4.31347275e+01, -4.54052048e+01, -4.74857635e+01],
        [-3.85544434e+01,  5.69763184e-01,  4.81357422e+01, ...,
         -4.62076416e+01, -4.81270828e+01, -5.05048599e+01],
        [ 3.77388916e+01,  5.33399048e+01,  9.03955078e+01, ...,
         -5.27753525e+01, -5.38565979e+01, -5.48468781e+01],
        ...,
        [-3.05555761e-02, -2.43055522e-02, -2.46527791e-02, ...,
         -8.57291698e-01, -8.34722281e-01, -8.14930558e-01],
        [-4.16666269e-03, -1.00694299e-02, -1.49305761e-02, ...,
         -8.63888979e-01, -8.41319442e-01, -8.42013955e-01],
        [-1.31944418e-02, -2.84722447e-02, -2.88194418e-02, ...,
         -8.65625024e-01, -8.49305630e-01, -8.53472233e-01]],

       [[-4.98767700e+01, -8.08298950e+01, -8.90302124e+01, ...,
          1.64365265e+02,  1.64198944e+02,  1.61712143e+02],
        [-6.45023804e+01, -9.25864868e+01, -9.04267578e+01, ...,
          1.67250702e+02,  1.62810425e+02,  1.60328491e+02],
        [-5.81569214e+01, -6.84309082e+01, -7.82919922e+01, ...,
          1.70703796e+02,  1.65789246e+02,  1.63111465e+02],
...
          2.87499905e-01,  2.74305820e-01,  2.97222614e-01],
        [-8.33333135e-02, -6.59722388e-02, -7.15278089e-02, ...,
          2.31249809e-01,  2.40972519e-01,  2.22916603e-01],
        [-7.56944418e-02, -9.09722149e-02, -9.44444239e-02, ...,
          7.63845444e-03, -5.06939888e-02, -6.25000000e-02]],

       [[-1.52736816e+02, -1.48377090e+02, -1.32940964e+02, ...,
         -6.91319466e+00, -6.86736107e+00, -6.70277786e+00],
        [-1.60094452e+02, -1.36577087e+02, -1.23269440e+02, ...,
         -6.51874924e+00, -6.38472176e+00, -6.21249962e+00],
        [-1.34864563e+02, -1.25337494e+02, -1.11315277e+02, ...,
         -6.81527710e+00, -6.73055458e+00, -6.63472366e+00],
        ...,
        [ 4.28472221e-01,  4.28472221e-01,  4.27083373e-01, ...,
          1.01666689e+00,  9.20139313e-01,  8.38889122e-01],
        [ 3.95833373e-01,  3.71527791e-01,  3.65972221e-01, ...,
          1.18958330e+00,  1.07430553e+00,  9.31250095e-01],
        [ 2.36805588e-01,  2.21527815e-01,  1.76388919e-01, ...,
          1.36180544e+00,  1.28263903e+00,  1.16666698e+00]]],
      dtype=float32)
Coordinates:
  * date       (date) object 'DJF 1991' 'DJF 1992' ... 'SON 2023' 'SON 2024'
  * latitude   (latitude) float64 -20.0 -19.75 -19.5 -19.25 ... 79.5 79.75 80.0
  * longitude  (longitude) float64 -50.0 -49.75 -49.5 -49.25 ... 79.5 79.75 80.0

In [6]:
import os
def export_to_geotiff(path, u_data, v_data, lat, lon, description):
    # Flip latitude if needed (GeoTIFF expects top-to-bottom order)
    if lat[0] > lat[-1]:
        u_data = u_data[::-1]
        v_data = v_data[::-1]
        lat = lat[::-1]

    # Get transform
    pixel_size_x = abs((lon[-1] - lon[0])) / (len(lon) - 1)
    pixel_size_y = abs((lat[-1] - lat[0])) / (len(lat) - 1)
    transform = from_origin(lon[0] - pixel_size_x / 2, lat[0] - pixel_size_y / 2, pixel_size_x, -pixel_size_y)

    # Stack u and v into a 3D array (bands, height, width)
    data = np.stack([u_data, v_data])  # shape: (2, lat, lon)

    with rasterio.open(
        path,
        'w',
        driver='GTiff',
        height=u_data.shape[0],
        width=u_data.shape[1],
        count=2,  # 2 bands: u and v
        dtype=u_data.dtype,
        crs="EPSG:4326",
        transform=transform,
        description=description
    ) as dst:
        dst.write(data[0], 1)  # Band 1 - u
        dst.write(data[1], 2)  # Band 2 - v
        
# Export regression slope map
output_dir = 'CAPE'  # no leading slash unless it's an absolute path
os.makedirs(output_dir, exist_ok=True)

for d in range(137):
    file_path = os.path.join(output_dir, str(anomalies['date'][d].values) + '.tif')
    export_to_geotiff(file_path, anomalies[d], pval[d], anomalies.latitude.values, anomalies.longitude.values, 'CAPE Seasonal Anomalies of '+str(anomalies['date'][d].values))